### ISSUE TITLE
Not sure if this error is caused by something on my end, or is an issue

### ISSUE THREAD

**Issue by dylanfurr** [jdsmith2816/facefixer#10]
The error in particular is `Settings.cs(10,21): error CS0246: The type or namespace name 'ModKey' could not be found (are you missing a using directive or an assembly reference?)` 

I tried reinstalling the patcher several times, tried switching from profile to latest, but nothing seems to be do it. Any help would be great appreciated. Thank you!

**Comment by Noggog** [comment]
My suggestion is make sure you're using the newest Synth UI, as mentioned here
https://github.com/Mutagen-Modding/Synthesis/wiki/Versioning

And then try following this FAQ
https://github.com/Mutagen-Modding/Synthesis/discussions/168
