### ISSUE TITLE
Patcher fails with a lot of "file not found" errors. 

### ISSUE THREAD

**Issue by HDMFanatic** [jdsmith2816/facefixer#14]
Not sure why this is happening as it never happened before, I've noticed there's been an update to the build in the last couple months though I'm not sure if that is causing the script to fail for me or not.
Log below:
[facefixer.txt](https://github.com/Synthesis-Collective/facefixer/files/13125635/facefixer.txt)

**Comment by Noggog** [comment]
Do you have Net SDK 7.0 installed?  Facefixer was updated to use 7 recently.
<https://github.com/Mutagen-Modding/Synthesis/wiki/Installation>

Do a `dotnet --info` and shoot back the results.

Let me know if that helps at all

**Comment by HDMFanatic** [comment]
This time I've installed the latest 7.0 SDK but now my other patchers are having a problem.

**Comment by Noggog** [comment]
Hop over to the discord, I'd say
https://discord.com/invite/53KMEsW

**Comment by Noggog** [comment]
Closing this.  Was related to DotNet SDK being broken somehow, and failing when certain build parameters were provided.  Unrelated to facefixer.

Will be following up in discord
