### ISSUE TITLE
'0 NPC's patched'

### ISSUE THREAD

**Issue by joanna2137** [jdsmith2816/facefixer#15]
I'm having an issues I've never had before with this patch, it always worked flawlessly. No matter my load order, it always ends up patching 0 NPC's with following log: 
`Compiling solution "C:\Users\Joanna\AppData\Local\Temp\Synthesis\lo1fbpov.i3q\Git\vq140fno.j34\Runner\FaceFixer\FaceFixer.csproj"
No extra data to consider
("C:\Users\Joanna\AppData\Local\Temp\Synthesis\lo1fbpov.i3q\Git\vq140fno.j34\Runner\FaceFixer"): "dotnet" "build \"FaceFixer.csproj\" --runtime win-x64 -c Release"
Compiled solution "C:\Users\Joanna\AppData\Local\Temp\Synthesis\lo1fbpov.i3q\Git\vq140fno.j34\Runner\FaceFixer\FaceFixer.csproj"
Sha "276f605efa705d7203db0f9fec42882f9a5e2d73"
Running
(""): "dotnet" "run --project \"C:\Users\Joanna\AppData\Local\Temp\Synthesis\lo1fbpov.i3q\Git\vq140fno.j34\Runner\FaceFixer\FaceFixer.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath \"D:\Aurora\Game Root\Data\" --ExtraDataFolder \"D:\Aurora\Tools\Synthesis\Data\Skyrim Special Edition\facefixer\" --FormIDRangeMode Auto --GameRelease SkyrimSE --ModKey Synthesis.esp --LoadOrderFilePath C:\Users\Joanna\AppData\Local\Temp\Synthesis\lo1fbpov.i3q\Workspace\Synthesis\Plugins.txt --LoadOrderIncludesCreationClub --OutputPath \"C:\Users\Joanna\AppData\Local\Temp\Synthesis\lo1fbpov.i3q\Workspace\Synthesis\1 - facefixer\Synthesis.esp\" --PatcherName facefixer --PersistencePath C:\Users\Joanna\AppData\Local\Temp\Synthesis\lo1fbpov.i3q\Persistence --SourcePath \"C:\Users\Joanna\AppData\Local\Temp\Synthesis\lo1fbpov.i3q\Workspace\Seed Mod\Synthesis.esp\""
Mutagen version: 0.26
Mutagen sha: 62dfefd50f356fc7c8f3a358640931a756c47019
Synthesis version: 0.14
Synthesis sha: 6be6ac02e83f1832b862d6e206d7e0499eeed685
run-patcher --DataFolderPath "D:\Aurora\Game Root\Data" --ExtraDataFolder "D:\Aurora\Tools\Synthesis\Data\Skyrim Special Edition\facefixer" --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\Joanna\AppData\Local\Temp\Synthesis\lo1fbpov.i3q\Workspace\Synthesis\Plugins.txt --OutputPath "C:\Users\Joanna\AppData\Local\Temp\Synthesis\lo1fbpov.i3q\Workspace\Synthesis\1 - facefixer\Synthesis.esp" --SourcePath "C:\Users\Joanna\AppData\Local\Temp\Synthesis\lo1fbpov.i3q\Workspace\Seed Mod\Synthesis.esp"
Prepping state.
Reading settings file: D:\Aurora\Tools\Synthesis\Data\Skyrim Special Edition\facefixer\settings.json
Files to map to:
Patched 0 Npcs
Running patch.
Writing to output: C:\Users\Joanna\AppData\Local\Temp\Synthesis\lo1fbpov.i3q\Workspace\Synthesis\1 - facefixer\Synthesis.esp`
I'm attaching my facxefixer settings. I've tried to change them up but nothing seemed to work. I'm using a stock game folder and running my synthesis through MO2. Plugins.txt in my Synthesis load order is correct for my LO. Does anyone have any idea what could be the issue? Thank you so much in advance! 
![Zrzut ekranu 2024-04-25 120442](https://github.com/Synthesis-Collective/facefixer/assets/143667263/034393d0-314a-4fbf-9209-1201880d976a)

**Comment by Noggog** [comment]
Hmm, not too familiar with facefixers gritty internals, but I know that facefixer does nothing when run "vanilla".   Very specific settings and intention must be outlined in its `Settings` pane for it to do anything.

So I would first check that the settings are still there that you expect (I dont see a picture of that pane here).  Did you design the settings yourself? Or get them from someone else?

**Comment by joanna2137** [comment]
> So I would first check that the settings are still there that you expect (I dont see a picture of that pane here). Did you design the settings yourself? Or get them from someone else?
I just picked a combination of appearance mods I have in my LO in the settings pane, and besides that they were all default - but the patcher failed no matter what combination of mods I put there. For some reason when I went back to modding after the holidays and rearranged my LO a bit, everything works perfectly now, I have no idea why XD Thank you for trying to help. I don't even know what the problem was, so I'm closing this issue
